// Role-Based Access Control (RBAC) definitions and permission checker

export const ROLES = {
  ADMIN: 'Admin',
  OFFICER: 'Officer',
  ATTORNEY: 'Attorney'
};

export const PERMISSIONS = {
  VIEW_DOCUMENT: 'VIEW_DOCUMENT',
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  EDIT_DOCUMENT: 'EDIT_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  APPROVE_DOCUMENT: 'APPROVE_DOCUMENT',
  DOWNLOAD_DOCUMENT: 'DOWNLOAD_DOCUMENT',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  MANAGE_USERS: 'MANAGE_USERS'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.APPROVE_DOCUMENT,
    PERMISSIONS.DOWNLOAD_DOCUMENT,
    PERMISSIONS.VIEW_AUDIT_LOG,
    PERMISSIONS.MANAGE_USERS
  ],
  [ROLES.OFFICER]: [
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.DOWNLOAD_DOCUMENT,
    PERMISSIONS.VIEW_AUDIT_LOG
  ],
  [ROLES.ATTORNEY]: [
    PERMISSIONS.VIEW_DOCUMENT,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DOWNLOAD_DOCUMENT
  ]
};

export const hasPermission = (userRole, permission) => {
  if (!userRole) return false;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(permission);
};

